/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Crypto;

import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.mail.MessagingException;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Andarias Silvanus
 */
public class EmailClient extends javax.swing.JFrame {

    MailReader MR;
    int numColumn = 3;
    String username = "";
    String password = "";
    String recipient = "";
    String subject = "";
    String content = "";
    int MsgIdx = 0;
    int inbox = 1;
    int sentMail = 2;
    int drafts = 3;
    int spam = 4;
    
    /**
     * Creates new form EmailClient
     */
    public EmailClient() throws MessagingException, IOException {
        setLocation (320,120);
        setTitle("GMail Email Client");
        initComponents();
        LoginDialog dialog = new LoginDialog(this);
        dialog.show();
        username = dialog.getUsername();
        password = dialog.getPassword();
        MR = new MailReader(username, password);
        MsgIdx = MR.getMessages().length-1;
        FillMsgArea();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        MsgTable = new javax.swing.JTable();
        MsgArea = new java.awt.TextArea();
        KirimBtn = new javax.swing.JButton();
        InboxBtn = new javax.swing.JButton();
        SentBtn = new javax.swing.JButton();
        DraftBtn = new javax.swing.JButton();
        SPAMBtn = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        MsgTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Pengirim", "Subject", "Tanggal"
            }
        ));
        jScrollPane1.setViewportView(MsgTable);

        KirimBtn.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        KirimBtn.setText("Kirim Email");
        KirimBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                KirimBtnActionPerformed(evt);
            }
        });

        InboxBtn.setText("Kotak Masuk");
        InboxBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InboxBtnActionPerformed(evt);
            }
        });

        SentBtn.setText("Kotak Keluar");
        SentBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SentBtnActionPerformed(evt);
            }
        });

        DraftBtn.setText("Kotak Draft");
        DraftBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DraftBtnActionPerformed(evt);
            }
        });

        SPAMBtn.setText("Kotak SPAM");
        SPAMBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SPAMBtnActionPerformed(evt);
            }
        });

        jButton6.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jButton6.setText("EXIT");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(KirimBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 142, Short.MAX_VALUE)
                    .addComponent(InboxBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(SentBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(DraftBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(SPAMBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(MsgArea, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 677, Short.MAX_VALUE))
                .addGap(19, 19, 19))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(KirimBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(InboxBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(SentBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(DraftBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(SPAMBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(MsgArea, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Tombol Inbox
    private void InboxBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InboxBtnActionPerformed
        FillMsgArea2(inbox);
    }//GEN-LAST:event_InboxBtnActionPerformed

    // Tombol Sent Box
    private void SentBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SentBtnActionPerformed
        FillMsgArea2(sentMail);
    }//GEN-LAST:event_SentBtnActionPerformed

    // Tombol Draft
    private void DraftBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DraftBtnActionPerformed
        FillMsgArea2(drafts);
    }//GEN-LAST:event_DraftBtnActionPerformed

    // Tombol SPAM
    private void SPAMBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SPAMBtnActionPerformed
        FillMsgArea2(spam);
    }//GEN-LAST:event_SPAMBtnActionPerformed

    // Tombol Exit
    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        dispose();
    }//GEN-LAST:event_jButton6ActionPerformed

    // Tombol Kirim
    private void KirimBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_KirimBtnActionPerformed
        ComposeDialog dialog = new ComposeDialog(this);
        dialog.show();
        recipient = dialog.getRecipient();
        subject = dialog.getSubject();
        content = dialog.getContent();
        System.out.println(content);
        SendGmail SG = new SendGmail();
        String[] to = {recipient};
        SG.sendFromGMail(username, password, to, subject, content);
    }//GEN-LAST:event_KirimBtnActionPerformed

    private void FillMsgArea2 (int type) {
        MR.ReadFolder(type);
        MsgIdx = MR.getMessages().length-1;
        if (MR.getMessages().length<100)
            while (MsgTable.getRowCount()>MR.getMessages().length)
                ((DefaultTableModel)MsgTable.getModel()).removeRow(MsgTable.getRowCount()-1);
        else
            ((DefaultTableModel)MsgTable.getModel()).setRowCount(100);
        try {
            FillMsgArea();
        }
        catch (MessagingException e) {
        }
        catch (IOException e) {
        }
    }
    
    private void FillMsgArea () throws MessagingException, IOException {
        int row = 0;
        while (row<100) {
            for (int j=0; j<3; j++) {
                if (j==0)
                    MsgTable.setValueAt("anda", row, j);
                else if (j==1)
                    MsgTable.setValueAt(MR.getMessages()[MsgIdx].getSubject(), row, j);
                else if (j==2)
                    MsgTable.setValueAt(MR.getMessages()[MsgIdx].getReceivedDate(), row, j);
            }
            row ++;
            MsgIdx--;
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EmailClient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EmailClient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EmailClient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EmailClient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new EmailClient().setVisible(true);
                EmailClient EC = null;
                try {
                    EC = new EmailClient();
                } catch (MessagingException ex) {
                    Logger.getLogger(EmailClient.class.getName()).log(Level.SEVERE, null, ex);
                } catch (IOException ex) {
                    Logger.getLogger(EmailClient.class.getName()).log(Level.SEVERE, null, ex);
                }
                EC.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton DraftBtn;
    private javax.swing.JButton InboxBtn;
    private javax.swing.JButton KirimBtn;
    private java.awt.TextArea MsgArea;
    private javax.swing.JTable MsgTable;
    private javax.swing.JButton SPAMBtn;
    private javax.swing.JButton SentBtn;
    private javax.swing.JButton jButton6;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
