/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Crypto;

import CipherBlock.Kristik;
import ecdsa.ECDSA;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.mail.MessagingException;
import javax.swing.JOptionPane;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author Andarias Silvanus
 */
public class EmailClient extends javax.swing.JFrame {
    ECDSA ecdsa;
    MailReader MR;
    int numColumn = 3;
    String username = "";
    String password = "";
    String recipient = "";
    String subject = "";
    String content = "";
    int MsgIdx = 0;
    int inbox = 1;
    int sentMail = 2;
    int drafts = 3;
    int spam = 4;
    
    /**
     * Creates new form EmailClient
     */
    public EmailClient() throws MessagingException, IOException {
        setLocation (320,120);
        setTitle("GMail Email Client");
        initComponents();
        LoginDialog dialog = new LoginDialog(this);
        dialog.show();
        username = dialog.getUsername();
        password = dialog.getPassword();
        MR = new MailReader(username, password);
        ecdsa = new ECDSA();
        MsgIdx = MR.getMessages().length-1;
        FillMsgArea(true);
        
        MsgTable.getSelectionModel().addListSelectionListener(new ListSelectionListener() {
            public void valueChanged(ListSelectionEvent e) {
                int row = MsgTable.getSelectedRow();
                MsgArea.setText("");
                try {
                    int idx = MR.getMessages().length - 1 - row;
                    System.out.println(MR.getMessages()[idx].getSubject());
                    String content = MR.getMessages()[idx].getContent().toString();
                    MsgArea.setText(content);
                    
                } catch (MessagingException ex) {
                    Logger.getLogger(EmailClient.class.getName()).log(Level.SEVERE, null, ex);
                } catch (IOException ex) {
                    Logger.getLogger(EmailClient.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        MsgTable = new javax.swing.JTable();
        KirimBtn = new javax.swing.JButton();
        InboxBtn = new javax.swing.JButton();
        SentBtn = new javax.swing.JButton();
        DraftBtn = new javax.swing.JButton();
        SPAMBtn = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        PublikBtn = new javax.swing.JButton();
        DekripsiBtn = new javax.swing.JButton();
        KunciBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        MsgTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Pengirim", "Subject", "Tanggal"
            }
        ));
        jScrollPane1.setViewportView(MsgTable);

        KirimBtn.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        KirimBtn.setText("Kirim Email");
        KirimBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                KirimBtnActionPerformed(evt);
            }
        });

        InboxBtn.setText("Kotak Masuk");
        InboxBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InboxBtnActionPerformed(evt);
            }
        });

        SentBtn.setText("Kotak Keluar");
        SentBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SentBtnActionPerformed(evt);
            }
        });

        DraftBtn.setText("Kotak Draft");
        DraftBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DraftBtnActionPerformed(evt);
            }
        });

        SPAMBtn.setText("Kotak SPAM");
        SPAMBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SPAMBtnActionPerformed(evt);
            }
        });

        jButton6.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jButton6.setText("EXIT");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        PublikBtn.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        PublikBtn.setText("Verifikasi Email");
        PublikBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PublikBtnActionPerformed(evt);
            }
        });

        DekripsiBtn.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        DekripsiBtn.setText("Dekripsi Pesan");
        DekripsiBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DekripsiBtnActionPerformed(evt);
            }
        });

        KunciBtn.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        KunciBtn.setText("Kunci Anda");
        KunciBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                KunciBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(KirimBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 142, Short.MAX_VALUE)
                    .addComponent(InboxBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(SentBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(DraftBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(SPAMBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(PublikBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(DekripsiBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(KunciBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(MsgArea, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 677, Short.MAX_VALUE))
                .addGap(19, 19, 19))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(KirimBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(InboxBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(SentBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(DraftBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(SPAMBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(MsgArea, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(PublikBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(DekripsiBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(KunciBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(22, 22, 22))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Tombol Inbox
    private void InboxBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InboxBtnActionPerformed
        FillMsgArea2(inbox);
    }//GEN-LAST:event_InboxBtnActionPerformed

    // Tombol Sent Box
    private void SentBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SentBtnActionPerformed
        FillMsgArea2(sentMail);
    }//GEN-LAST:event_SentBtnActionPerformed

    // Tombol Draft
    private void DraftBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DraftBtnActionPerformed
        FillMsgArea2(drafts);
    }//GEN-LAST:event_DraftBtnActionPerformed

    // Tombol SPAM
    private void SPAMBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SPAMBtnActionPerformed
        FillMsgArea2(spam);
    }//GEN-LAST:event_SPAMBtnActionPerformed

    // Tombol Exit
    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        dispose();
    }//GEN-LAST:event_jButton6ActionPerformed

    // Tombol Kirim
    private void KirimBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_KirimBtnActionPerformed
        ComposeDialog dialog = new ComposeDialog(this);
        dialog.show();
        recipient = dialog.getRecipient();
        subject = dialog.getSubject();
        content = dialog.getContent();
        SendGmail SG = new SendGmail();
        String[] to = {recipient};
        SG.KEY = dialog.key;
        SG.sendFromGMail(username, password, to, subject, content);
    }//GEN-LAST:event_KirimBtnActionPerformed
                                    
    // Tombol Generate Kunci
    private void KunciBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_KunciBtnActionPerformed
        try {
            KunciDialog dialog = new KunciDialog(this);
            dialog.show();
            ecdsa.setdA(dialog.getPriKey());
            ecdsa.setQA(dialog.getPubKey());
        } catch (IOException ex) {
            Logger.getLogger(EmailClient.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_KunciBtnActionPerformed

    private void DekripsiBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DekripsiBtnActionPerformed
        // TODO add your handling code here:
        KunciDekripsiDialog dialog = new KunciDekripsiDialog(this);
        dialog.show();
        Kristik decipher = new Kristik();
        decipher.setKey(dialog.getKey());
        MsgArea.setText(decipher.decECB(MsgArea.getText()));
    }//GEN-LAST:event_DekripsiBtnActionPerformed

    private void PublikBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PublikBtnActionPerformed
        // TODO add your handling code here:
        KunciPublikDialog dialog = new KunciPublikDialog(this);
        dialog.show();
        ecdsa.setQA(dialog.getPublikKey());
        String signature = MsgArea.getText().substring(MsgArea.getText().indexOf("<<"));
        String message = MsgArea.getText().substring(0, MsgArea.getText().indexOf("<<")-4);
        System.out.println(message);
        System.out.println(signature);
        signature = signature.substring(2);
        System.out.println(signature);
        boolean verify = false;
        verify = ecdsa.checkSignature(message, signature);
        System.out.println(verify);
        if (verify){
            JOptionPane.showMessageDialog(this,
                    "Pesan valid",
                    "Missing Setting(s)", JOptionPane.PLAIN_MESSAGE);
            return;
        } else {
            JOptionPane.showMessageDialog(this,
                    "Pesan tidak  valid",
                    "Missing Setting(s)", JOptionPane.ERROR_MESSAGE);
            return;
        }
    }//GEN-LAST:event_PublikBtnActionPerformed
    
    private void FillMsgArea2 (int type) {
        MR.ReadFolder(type);
        MsgIdx = MR.getMessages().length-1;
        if (MR.getMessages().length<100)
            while (MsgTable.getRowCount()>MR.getMessages().length)
                ((DefaultTableModel)MsgTable.getModel()).removeRow(MsgTable.getRowCount()-1);
        else
            ((DefaultTableModel)MsgTable.getModel()).setRowCount(100);
        try {
            if (type==2)
                FillMsgArea(false);
            else
                FillMsgArea(true);
        }
        catch (MessagingException e) {
        }
        catch (IOException e) {
        }
    }
    
    private void FillMsgArea (boolean tipe) throws MessagingException, IOException {
        // tipe = false u/ sent mail
        // tipe = true u/ inbox, draft, SPAM
        int row = 0;
        while (row<100) {
            for (int j=0; j<3; j++) {
                if (j==0)
//                    MsgTable.setValueAt(MR.SenderName.get(MsgIdx), row, j);
                    if (tipe)
                        MsgTable.setValueAt(MR.SenderName.get(row), row, j);
                    else
                        MsgTable.setValueAt(MR.ReceiverName.get(row), row, j);
                else if (j==1)
                    MsgTable.setValueAt(MR.getMessages()[MsgIdx].getSubject(), row, j);
                else if (j==2)
                    MsgTable.setValueAt(MR.getMessages()[MsgIdx].getReceivedDate(), row, j);
            }
            row ++;
            MsgIdx--;
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EmailClient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EmailClient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EmailClient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EmailClient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new EmailClient().setVisible(true);
                EmailClient EC = null;
                try {
                    EC = new EmailClient();
                } catch (MessagingException ex) {
                    Logger.getLogger(EmailClient.class.getName()).log(Level.SEVERE, null, ex);
                } catch (IOException ex) {
                    Logger.getLogger(EmailClient.class.getName()).log(Level.SEVERE, null, ex);
                }
                EC.setVisible(true);
                
//                EC.MsgTable.getSelectionModel().addListSelectionListener(new ListSelectionListener(){
//                    public void valueChanged(ListSelectionEvent event) {
//                        // do some actions here, for example
//                        // print first column value from selected row
//                        System.out.println(EC.MsgTable.getValueAt(EC.MsgTable.getSelectedRow(), 0).toString());
//                        EC.MsgArea.setText("");
//                        
//                    }
//                });
                
//                TableColumnModelListener tableColumnModelListener;
//                tableColumnModelListener = new TableColumnModelListener() {
//                    @Override
//                    public void columnSelectionChanged(ListSelectionEvent e) {
//                        SwingUtilities.invokeLater(new Runnable() {
//                            @Override
//                            public void run() {
////                                System.out.println(EC.MsgTable.getSelectedColumn()); // this is correct
////                                System.out.println(EC.MsgTable.getSelectedRow());  // -1 on first click in JTable
//                                EC.MsgArea.setText("");
//                            }
//                        });
//                    }
//
//                    @Override
//                    public void columnAdded(TableColumnModelEvent e) {
//                        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
//                    }
//
//                    @Override
//                    public void columnRemoved(TableColumnModelEvent e) {
//                        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
//                    }
//
//                    @Override
//                    public void columnMoved(TableColumnModelEvent e) {
//                        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
//                    }
//
//                    @Override
//                    public void columnMarginChanged(ChangeEvent e) {
//                        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
//                    }
//                };
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton DekripsiBtn;
    private javax.swing.JButton DraftBtn;
    private javax.swing.JButton InboxBtn;
    private javax.swing.JButton KirimBtn;
    private javax.swing.JButton KunciBtn;
    private final java.awt.TextArea MsgArea = new java.awt.TextArea();
    private javax.swing.JTable MsgTable;
    private javax.swing.JButton PublikBtn;
    private javax.swing.JButton SPAMBtn;
    private javax.swing.JButton SentBtn;
    private javax.swing.JButton jButton6;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
