/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Crypto;

import ecdsa.ECDSA;
import java.awt.*;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.math.BigInteger;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Andarias Silvanus
 */
public class KunciDialog extends javax.swing.JDialog {
    private ECDSA ecdsa;
    /**
     * Creates new form KunciDialog
     */
    public KunciDialog(Frame parent) throws IOException {
        // Call super constructor, specifying that dialog is modal.
        super(parent, true);
        
        // Set dialog title.
        setTitle("Kunci Anda");
        setLocation (400,150);
        initComponents();
        ecdsa = new ECDSA();
        File f = new File(".pri");
        if(f.exists() && !f.isDirectory()) {
            readPrivateKey();
            KunciPrivatField.setText(ecdsa.getdA().toString());
        }
        File f2 = new File(".pub");
        if(f2.exists() && !f2.isDirectory()) {
            readPublicKey();
            KunciPublikXField.setText(ecdsa.getQA().getX().toString());
            KunciPublikYField.setText(ecdsa.getQA().getY().toString());
        }
    }
    
    // Get private key
    public BigInteger getPriKey() {
        return ecdsa.getdA();
    }
    
    // Get public key
    public ecdsa.Point getPubKey() {
        return ecdsa.getQA();
    }
    
    //Save private key into *.pri file
    private void savePrivateKey() throws FileNotFoundException, IOException{
        String file = ".pri";
        byte[] bytes = ecdsa.getdA().toByteArray();
        FileOutputStream stream = new FileOutputStream(file);
        try {
            stream.write(bytes);
        } finally {
            stream.close();
        }
    }
    
    //Save public key into *.pub file
    private void savePublicKey() throws IOException{
        String file = ".pub";
        byte[] bytes = ecdsa.getQA().toHexString().getBytes();
        FileOutputStream stream = new FileOutputStream(file);
        try {
            stream.write(bytes);
        } finally {
            stream.close();
        }
    }
    
    //Read private key from .pri file
    private void readPrivateKey() throws IOException{
        String file = ".pri";
        Path path = Paths.get(file);
        byte[] bytes = Files.readAllBytes(path);
        BigInteger privateKey = new BigInteger(bytes);
        ecdsa.setdA(privateKey);
    }
    
    //Read public key from .pub file
    private void readPublicKey() throws IOException{
        String file = ".pub";
        Path path = Paths.get(file);
        byte[] bytes = Files.readAllBytes(path);
        String str = new String(bytes);
        int len = str.length();
        ecdsa.Point signPoint = new ecdsa.Point();
        signPoint.setX(new BigInteger(str.substring(0, len/2), 16));
        signPoint.setY(new BigInteger(str.substring(len/2), 16));
        ecdsa.setQA(signPoint);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TitleLabel = new javax.swing.JLabel();
        KunciPrivatLabel = new javax.swing.JLabel();
        KunciPublikXLabel = new javax.swing.JLabel();
        KunciPrivatField = new javax.swing.JTextField();
        BangkitkanBtn = new javax.swing.JButton();
        KunciPublikYLabel = new javax.swing.JLabel();
        CloseBtn = new javax.swing.JButton();
        KunciPublikXField = new javax.swing.JTextField();
        KunciPublikYField = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        TitleLabel.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        TitleLabel.setText("Kunci Anda");

        KunciPrivatLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        KunciPrivatLabel.setText("Kunci Privat");

        KunciPublikXLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        KunciPublikXLabel.setText("Kunci Publik X");

        KunciPrivatField.setEditable(false);

        BangkitkanBtn.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        BangkitkanBtn.setText("Bangkitkan");
        BangkitkanBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BangkitkanBtnActionPerformed(evt);
            }
        });

        KunciPublikYLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        KunciPublikYLabel.setText("Kunci Publik Y");

        CloseBtn.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        CloseBtn.setText("Close");
        CloseBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CloseBtnActionPerformed(evt);
            }
        });

        KunciPublikXField.setEditable(false);

        KunciPublikYField.setEditable(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(KunciPrivatLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(KunciPublikXLabel, javax.swing.GroupLayout.Alignment.TRAILING))
                            .addComponent(KunciPublikYLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(KunciPublikXField)
                            .addComponent(KunciPrivatField, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(KunciPublikYField))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(TitleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(57, 57, 57))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(BangkitkanBtn)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(CloseBtn)
                                .addContainerGap())))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(TitleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(KunciPrivatLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(KunciPrivatField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(KunciPublikXLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(KunciPublikXField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(KunciPublikYLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(KunciPublikYField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BangkitkanBtn)
                    .addComponent(CloseBtn))
                .addContainerGap(13, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BangkitkanBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BangkitkanBtnActionPerformed
        ecdsa.generateKey();
        KunciPrivatField.setText(ecdsa.getdA().toString());
        KunciPublikXField.setText(ecdsa.getQA().getX().toString());
        KunciPublikYField.setText(ecdsa.getQA().getY().toString());
        try {
            savePrivateKey();
            savePublicKey();
        } catch (IOException ex) {
            Logger.getLogger(KunciDialog.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_BangkitkanBtnActionPerformed

    private void CloseBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CloseBtnActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_CloseBtnActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BangkitkanBtn;
    private javax.swing.JButton CloseBtn;
    private javax.swing.JTextField KunciPrivatField;
    private javax.swing.JLabel KunciPrivatLabel;
    private javax.swing.JTextField KunciPublikXField;
    private javax.swing.JLabel KunciPublikXLabel;
    private javax.swing.JTextField KunciPublikYField;
    private javax.swing.JLabel KunciPublikYLabel;
    private javax.swing.JLabel TitleLabel;
    // End of variables declaration//GEN-END:variables
}
